name: CI

on:
  pull_request:
    branches: [main, next]
  push:
    branches: [main, next]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: node -v

      - run: bun install

      - run: bun run lint

      - run: bun run dev:prepare

      - run: bun run test
